### ISSUE TITLE
setup/E0: require multiple patches as practice for later assignments like P0

### ISSUE THREAD

**Issue by theyoyojo** [underground-software/ILKD_course_materials#72]

**Comment by NinteMars** [comment]
Personally, I think that while doing multiple patches for setup is fine, doing so with E0 may be better. With setup being the first assignment, it might be better for the first submission to be as simple as possible with one patch so that students can get familiar with the command. Then, with E0, it moves to using two patches for practice.

Maybe for E0, before compiling the kernel, the user makes a copy of E0.txt in their username folder (potentially in username/E0 and not just username/ like the assignment specifies). Then, before making their first commit, they add the initial output of `uname -a` for a question before being asked for the number of attempts. I think this:
- Makes E0 use two patches without significantly changing the assignment or grading
- Makes it clear to the student, the peer reviewer, and the grader that when they answer the next questions after compiling the kernel, they have successfully booted into their kernel. The output for `uname -a` should be different
- Allows for a potential partial initial submission, as the student would have answered 1 of the questions. Currently, if the student runs into issues when trying to build, install and boot into the kernel and can't complete the assignment in time, the only option is to submit an empty, unmodified E0.

There is another option that would be simpler, and that is to simply have the first commit be adding E0 to their username folder, unmodified. The second patch will be actually answering the questions. This creates multiple patches, but doesn't have some of the potential upsides to adding the additional `uname -a` question to the assignment.

**Comment by charliemirabile** [comment]
I think that setup is easy enough even if it has two patches which is why I merged #87. Suggestions about E0 are valid though.

**Comment by charliemirabile** [comment]
Created new issues #100 and #99 to address leftovers related to E0
